apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_django_pro
  labels:
    app: test_django_pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test_django_pro
  template:
    metadata:
      labels:
        app: test_django_pro
    spec:
      containers:
      - name: test_django_pro
        image: ridhindas/django-app
        ports:
        - containerPort: 8080
